
### --------------------------------------------------------
###  Next: Configuration macro of nexus.
### --------------------------------------------------------

/Geometry/NextNew/pressure 10.1 bar
/Geometry/NextNew/elfield false

/nexus/random_seed {random_seed}
# /nexus/random_seed 0


### GENERATOR
/Generator/SingleParticle/min_energy 1.0 MeV
/Generator/SingleParticle/max_energy 2.0 MeV
/Generator/SingleParticle/region ACTIVE

# PHYSICS
/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false

### VERBOSITIES
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

### JOB CONTROL
/nexus/persistency/outputFile nexus_ACTIVE_10bar_SINGLE_E_{file_index}.next

/nexus/persistency/start_id 1000000
